[package]
name = "dtl"
version = "0.0.1"
description = "Django Template Language for Rust"
authors = ["Vladislav Orlov <orlov@tesjin.ru>"]
repository = "https://github.com/tesjin/rust-dtl"
readme = "README.md"
license = "MIT"

[dependencies]
mopa = "0.2"